name: Publish Workflow

on:
  release:
    types: [ published ]

  workflow_dispatch:

jobs:
  npm-publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14.x
          registry-url: 'https://registry.npmjs.org'

      # Installs npm modules
      - name: Install
        run: npm install

      # Prepares the libs
      - name: Prepare
        run: npm run prepare
      
      # Publishes to NPM
      - name: Publish to NPM
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
