name: Unit Test Workflow

on:
  push:
    paths: [ '**/*' ]
    branches: [ main ]
  pull_request:
    paths: [ '**/*' ]
    branches: [ main ]

  workflow_dispatch:

jobs:
  unit-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      # Installs npm modules
      - name: Install
        run: npm install

      # Runs unit tests
      - name: Test 
        run: npm test
